### ISSUE TITLE
Empty string is converted to "s"

### ISSUE THREAD

**Issue by kasium** [atteo/evo-inflector#19]
Hi,
if I call `English.plural("")` I get "s". This maybe is related to this line: 
`categoryRule(CATEGORY_MAN_MANS, "", "s");`

BR,
Kai

**Comment by kasium** [comment]
This repo seems dead :-(

**Comment by sentinelt** [comment]
Well, I still maintain it (and several others at github/atteo). Just haven't got spare time to look at this issue, sorry. Will gladly accept a pull request though.

**Comment by kasium** [comment]
Thanks for the update. I'll prepare one
