### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by konkos** [atteo/evo-inflector#23]
I am thinking about using this to a project of mine. Should I consider it as a viable option?

**Comment by sentinelt** [comment]
You asked two questions:

> Is this repo dead?

No

> Should I consider is as a viable option?

There are more or less half a million downloads of Evo Inflector from Maven Central each month. 

![image](https://user-images.githubusercontent.com/53065/125164065-9a961780-e190-11eb-887f-cc422d0b1d84.png)

It is used by many high profile projects like [Spring and JetBrains](https://mvnrepository.com/artifact/org.atteo/evo-inflector/usages) and [tons of smaller projects](https://github.com/atteo/evo-inflector/network/dependents).

I believe you are good to go.
