### ISSUE TITLE
plural("loaf") should be "loaves" instead of "loafs"

### ISSUE THREAD

**Issue by Chessray** [atteo/evo-inflector#25]
The call `English.plural("loaf")` returns the String `loafs`. It should be `loaves`.

**Comment by sentinelt** [comment]
This library implements an algorithm to calculate plural form. It also contains a hardcoded plural forms for a limited number of a most frequent irregular words. Although it returns a valid response for 96% of all countable nouns in English language, with the remaining 4% there is still chance to get the wrong answer.

As part of the tests of this library the report is created which lists all the discrepancies between what this library returns and what Wiktionary gives as a correct answer. You can see [here](reports/incorrect-countable.md) that 'loaf' is already on this list - so we already know there is a problem with it.

I'm open to any ideas how to improve the algorithm to give better results, but as a rule I don't want to include every irregular word. And based on data from [wordfrequency.info](https://www.wordfrequency.info/samples/lemmas_60k.txt) 'loaf' is at the 29145 position in the frequency list.

**Comment by onacit** [comment]
@sentinelt The *here* link is dead. Thanks.

**Comment by sentinelt** [comment]
It's here: https://github.com/atteo/evo-inflector/blob/master/reports/incorrect-countable.md
