### ISSUE TITLE
Some uppercase words are pluralized to lowercase.

### ISSUE THREAD

**Issue by patrodyne** [atteo/evo-inflector#29]
Thank you for working on this challenging problem! I found some _uppercase_ words that are pluralized to _lowercase_. Instead, I expect a singular like "Foot" would pluralize to "Feet" and not to "feet". Here is a table of some words that preserve case and others that do not.

| Singular | Plural   | Preserved |
| -------- | -------- | --------- |
| Axis     | Axes     |    yes    |
| Child    | Children |    yes    |
| Foot     | feet     |    no     |
| Goose    | geese    |    no     |
| Leaf     | Leaves   |    yes    |
| Man      | men      |    no     |
| Mouse    | Mice     |    yes    |
| Tooth    | teeth    |    no     |
| Wife     | Wives    |    yes    |

To demonstrate, I have attached a small tar-ball containing a command line program to invoke `org.atteo.evo.inflector.English.plural("arg")` for arbitrary arguments (words): [evo-inflector-main.tar.gz](https://github.com/atteo/evo-inflector/files/10097111/evo-inflector-main.tar.gz)

**Comment by sentinelt** [comment]
Thank you for very detailed bug report. Indeed there was an issue with preserving of letter capitalization for irregular words. I fixed this in master branch and this fix will be available in the next release.
